version: '3.9'

services:

  server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: goapp_server
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - 3000:8080